import Foundation

/// Static, hand-curated index of every actionable row across panes. Mirrors
/// what the panes actually render — when a pane gains a row, add an entry
/// here too. The catalog is the source of truth for global search; building
/// it dynamically from view bodies would couple too tightly to SwiftUI internals.
enum SearchCatalog {
    static let rows: [SearchableRow] = [
        // MARK: Appearance
        .init(id: "theme",
              pane: .appearance,
              title: "Theme",
              subtitle: "Color palette",
              docKey: "theme",
              keywords: ["color", "palette", "scheme", "dark", "light"]),
        .init(id: "theme-pair",
              pane: .appearance,
              title: "Match system appearance",
              subtitle: "Use a light + dark theme pair",
              docKey: "theme",
              keywords: ["auto", "dark mode", "light mode", "system"]),
        .init(id: "background-opacity",
              pane: .appearance,
              title: "Background opacity",
              subtitle: "Transparent ↔ Opaque",
              docKey: "background-opacity",
              keywords: ["transparency", "alpha", "translucent"]),
        .init(id: "background-blur",
              pane: .appearance,
              title: "Background blur",
              subtitle: "Vibrancy behind the terminal",
              docKey: "background-blur",
              keywords: ["vibrancy", "frost"]),
        .init(id: "background",
              pane: .appearance,
              title: "Background color",
              subtitle: "Override the theme's background",
              docKey: "background",
              keywords: ["color", "bg", "hex"]),
        .init(id: "foreground",
              pane: .appearance,
              title: "Foreground color",
              subtitle: "Override the theme's text color",
              docKey: "foreground",
              keywords: ["color", "fg", "text", "hex"]),
        .init(id: "cursor-color",
              pane: .appearance,
              title: "Cursor color",
              docKey: "cursor-color",
              keywords: ["caret", "color"]),
        .init(id: "selection-background",
              pane: .appearance,
              title: "Selection background",
              docKey: "selection-background",
              keywords: ["highlight", "color"]),
        .init(id: "selection-foreground",
              pane: .appearance,
              title: "Selection foreground",
              docKey: "selection-foreground",
              keywords: ["highlight", "text", "color"]),
        .init(id: "bold-color",
              pane: .appearance,
              title: "Bold color",
              subtitle: "Color used for bold text",
              docKey: "bold-color",
              keywords: ["bright", "weight", "color"]),
        .init(id: "minimum-contrast",
              pane: .appearance,
              title: "Minimum contrast",
              subtitle: "Enforce fg/bg contrast ratio",
              docKey: "minimum-contrast",
              keywords: ["accessibility", "wcag", "contrast"]),

        // MARK: Window
        .init(id: "macos-titlebar-style",
              pane: .window,
              title: "Title bar style",
              docKey: "macos-titlebar-style",
              keywords: ["chrome", "header"]),
        .init(id: "macos-window-buttons",
              pane: .window,
              title: "Window buttons",
              subtitle: "Traffic-light visibility",
              docKey: "macos-window-buttons",
              keywords: ["traffic lights", "close", "minimize", "zoom"]),
        .init(id: "window-decoration",
              pane: .window,
              title: "Window decoration",
              docKey: "window-decoration",
              keywords: ["frame", "border", "borderless", "chrome"]),
        .init(id: "macos-window-shadow",
              pane: .window,
              title: "Window shadow",
              docKey: "macos-window-shadow"),
        .init(id: "window-padding-x",
              pane: .window,
              title: "Horizontal padding",
              docKey: "window-padding-x",
              keywords: ["margin", "space", "gutter"]),
        .init(id: "window-padding-y",
              pane: .window,
              title: "Vertical padding",
              docKey: "window-padding-y",
              keywords: ["margin", "space", "gutter"]),
        .init(id: "window-padding-balance",
              pane: .window,
              title: "Balance padding",
              docKey: "window-padding-balance"),
        .init(id: "macos-non-native-fullscreen",
              pane: .window,
              title: "Non-native fullscreen",
              docKey: "macos-non-native-fullscreen",
              keywords: ["fullscreen", "spaces"]),
        .init(id: "window-save-state",
              pane: .window,
              title: "Restore windows",
              subtitle: "Persist window state across launches",
              docKey: "window-save-state",
              keywords: ["session", "reopen", "state"]),

        // MARK: Font
        .init(id: "font-family",
              pane: .font,
              title: "Font family",
              docKey: "font-family",
              keywords: ["typeface", "monospace"]),
        .init(id: "font-size",
              pane: .font,
              title: "Font size",
              docKey: "font-size",
              keywords: ["zoom", "text size"]),
        .init(id: "font-feature-liga",
              pane: .font,
              title: "Standard ligatures",
              subtitle: "OpenType `liga` feature",
              docKey: "font-feature",
              keywords: ["ligatures", "opentype"]),
        .init(id: "font-feature-calt",
              pane: .font,
              title: "Contextual alternates",
              subtitle: "OpenType `calt` feature",
              docKey: "font-feature",
              keywords: ["ligatures", "opentype"]),
        .init(id: "font-thicken",
              pane: .font,
              title: "Thicken strokes",
              subtitle: "Bold text on non-Retina",
              docKey: "font-thicken",
              keywords: ["bold", "weight"]),

        // MARK: Cursor
        .init(id: "cursor-style",
              pane: .cursor,
              title: "Cursor style",
              subtitle: "Block, bar, underline",
              docKey: "cursor-style",
              keywords: ["caret", "shape"]),
        .init(id: "cursor-style-blink",
              pane: .cursor,
              title: "Blink cursor",
              docKey: "cursor-style-blink",
              keywords: ["blinking", "flash"]),
        .init(id: "cursor-opacity",
              pane: .cursor,
              title: "Cursor opacity",
              docKey: "cursor-opacity",
              keywords: ["transparency", "alpha"]),
        .init(id: "cursor-click-to-move",
              pane: .cursor,
              title: "Click to move cursor",
              docKey: "cursor-click-to-move",
              keywords: ["mouse", "click"]),
        .init(id: "mouse-hide-while-typing",
              pane: .cursor,
              title: "Hide mouse while typing",
              docKey: "mouse-hide-while-typing"),

        // MARK: Keyboard
        .init(id: "keybind",
              pane: .keyboard,
              title: "Custom shortcuts",
              subtitle: "Add and edit key bindings",
              docKey: "keybind",
              keywords: ["hotkey", "shortcut", "binding", "keyboard", "kbd"]),

        // MARK: Shell
        .init(id: "shell-integration",
              pane: .shell,
              title: "Shell integration",
              subtitle: "Auto, off, or a specific shell",
              docKey: "shell-integration",
              keywords: ["zsh", "bash", "fish", "elvish"]),
        .init(id: "shell-feature-cursor",
              pane: .shell,
              title: "Update cursor shape",
              docKey: "shell-integration-features"),
        .init(id: "shell-feature-sudo",
              pane: .shell,
              title: "Quote arguments to sudo",
              docKey: "shell-integration-features"),
        .init(id: "shell-feature-title",
              pane: .shell,
              title: "Update window title from shell",
              docKey: "shell-integration-features",
              keywords: ["title"]),
        .init(id: "command",
              pane: .shell,
              title: "Command",
              subtitle: "Override the launched shell",
              docKey: "command",
              keywords: ["shell", "exec", "startup"]),
        .init(id: "working-directory",
              pane: .shell,
              title: "Working directory",
              subtitle: "Initial cwd",
              docKey: "working-directory",
              keywords: ["cwd", "pwd", "directory"]),
        .init(id: "term",
              pane: .shell,
              title: "TERM",
              subtitle: "Terminfo identifier",
              docKey: "term",
              keywords: ["terminfo", "xterm"]),

        // MARK: Clipboard & Mouse
        .init(id: "clipboard-read",
              pane: .clipboardMouse,
              title: "Allow reading clipboard",
              docKey: "clipboard-read",
              keywords: ["paste", "permission", "security"]),
        .init(id: "clipboard-write",
              pane: .clipboardMouse,
              title: "Allow writing clipboard",
              docKey: "clipboard-write",
              keywords: ["copy", "permission", "security"]),
        .init(id: "clipboard-paste-protection",
              pane: .clipboardMouse,
              title: "Paste protection",
              subtitle: "Warn before risky pastes",
              docKey: "clipboard-paste-protection",
              keywords: ["security", "newline", "phishing"]),
        .init(id: "clipboard-trim-trailing-spaces",
              pane: .clipboardMouse,
              title: "Trim trailing spaces on paste",
              docKey: "clipboard-trim-trailing-spaces"),
        .init(id: "copy-on-select",
              pane: .clipboardMouse,
              title: "Copy on select",
              docKey: "copy-on-select",
              keywords: ["copy", "selection"]),
        .init(id: "selection-clear-on-typing",
              pane: .clipboardMouse,
              title: "Clear selection when typing",
              docKey: "selection-clear-on-typing"),
        .init(id: "mouse-shift-capture",
              pane: .clipboardMouse,
              title: "Shift capture",
              subtitle: "Shift+click selection vs. forward",
              docKey: "mouse-shift-capture"),
        .init(id: "mouse-scroll-multiplier",
              pane: .clipboardMouse,
              title: "Scroll multiplier",
              docKey: "mouse-scroll-multiplier",
              keywords: ["wheel", "trackpad", "scroll speed"]),
        .init(id: "mouse-reporting",
              pane: .clipboardMouse,
              title: "Forward mouse events to apps",
              docKey: "mouse-reporting",
              keywords: ["xterm-mouse", "vim mouse", "tmux mouse"]),
        .init(id: "focus-follows-mouse",
              pane: .clipboardMouse,
              title: "Focus follows mouse",
              docKey: "focus-follows-mouse",
              keywords: ["sloppy focus"]),

        // MARK: General
        .init(id: "auto-update",
              pane: .general,
              title: "Automatic updates",
              docKey: "auto-update",
              keywords: ["sparkle", "update"]),
        .init(id: "auto-update-channel",
              pane: .general,
              title: "Update channel",
              subtitle: "Stable or Tip",
              docKey: "auto-update-channel",
              keywords: ["beta", "nightly", "tip"]),
        .init(id: "confirm-close-surface",
              pane: .general,
              title: "Confirm before closing",
              docKey: "confirm-close-surface",
              keywords: ["quit", "exit"]),
        .init(id: "quit-after-last-window-closed",
              pane: .general,
              title: "Quit when last window closes",
              docKey: "quit-after-last-window-closed",
              keywords: ["dock"]),
        .init(id: "desktop-notifications",
              pane: .general,
              title: "Desktop notifications",
              docKey: "desktop-notifications",
              keywords: ["notify", "alert"]),
        .init(id: "bell-audio-volume",
              pane: .general,
              title: "Bell volume",
              docKey: "bell-audio-volume",
              keywords: ["sound", "audio", "alert"]),
        .init(id: "macos-auto-secure-input",
              pane: .general,
              title: "Enable secure input at password prompts",
              docKey: "macos-auto-secure-input",
              keywords: ["security", "password"]),
        .init(id: "macos-secure-input-indication",
              pane: .general,
              title: "Show secure-input indicator",
              docKey: "macos-secure-input-indication",
              keywords: ["security", "indicator"]),

        // MARK: About
        .init(id: "about",
              pane: .about,
              title: "About",
              subtitle: "Version and credits",
              keywords: ["version", "credits", "license"])
    ]
}
